import React, { useEffect, useState } from 'react';
import {
  Boxes,
  RotateCcw,
  AlertTriangle,
  FileDown,
  ArrowRight,
  TrendingDown,
  TrendingUp,
  Activity,
} from 'lucide-react';
import { getRefactorProposals, simulateRefactorProposal } from '../../api/client';
import { RefactorProposalDTO } from '../../types';

interface RefactoringHubProps {
  repositoryId?: string | null;
  analysisId?: string | null;
}

export const RefactoringHub: React.FC<RefactoringHubProps> = ({
  repositoryId,
  analysisId,
}) => {
  const [proposals, setProposals] = useState<RefactorProposalDTO[]>([]);
  const [selectedProposal, setSelectedProposal] = useState<RefactorProposalDTO | null>(null);
  const [loading, setLoading] = useState(false);
  const [simulating, setSimulating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!repositoryId || !analysisId) {
      // Mock proposal if no active analysis
      const mockProp: RefactorProposalDTO = {
        id: 'REF-PROP-001',
        target_rule_id: 'ARC-006',
        refactoring_type: 'DEPENDENCY_INVERSION',
        title: 'Break Circular Dependency between Auth & User Services',
        problem_statement: 'Circular dependency detected across cycle: auth_service -> token_manager -> user_service -> auth_service.',
        proposed_design: 'Extract IAuthenticationProvider interface in core/contracts. Invert user_service to consume interface rather than concrete auth_service.',
        affected_components: ['auth_service', 'token_manager', 'user_service'],
        affected_files: ['services/auth.py', 'services/user.py', 'services/tokens.py'],
        hypothetical_edge_mutations: [
          { action: 'REMOVE', source: 'user_service', target: 'auth_service' },
          { action: 'ADD', source: 'user_service', target: 'core.contracts' },
        ],
        simulated_metric_deltas: {
          auth_service: { delta_ca: -1, delta_ce: 0, delta_instability: 0.25 },
          user_service: { delta_ca: 0, delta_ce: 0, delta_instability: 0 },
        },
        simulation_status: 'VERIFIED_SIMULATION',
        status: 'PROPOSAL_ONLY',
        created_at: new Date().toISOString(),
      };
      setProposals([mockProp]);
      setSelectedProposal(mockProp);
      return;
    }

    setLoading(true);
    getRefactorProposals(repositoryId, analysisId)
      .then((data) => {
        setProposals(data);
        if (data.length > 0) setSelectedProposal(data[0]);
      })
      .catch((err) => {
        setError(err.message || 'Failed to load refactoring proposals.');
      })
      .finally(() => setLoading(false));
  }, [repositoryId, analysisId]);

  const handleSimulateRerun = async () => {
    if (!repositoryId || !analysisId || !selectedProposal) return;

    setSimulating(true);
    setError(null);

    try {
      const res = await simulateRefactorProposal(
        repositoryId,
        analysisId,
        selectedProposal.id,
        selectedProposal.hypothetical_edge_mutations
      );
      setSelectedProposal({
        ...selectedProposal,
        simulated_metric_deltas: res.metric_deltas,
        simulation_status: res.simulation_status,
      });
    } catch (err: any) {
      setError(err.message || 'Simulation rerun failed.');
    } finally {
      setSimulating(false);
    }
  };

  const handleExportRFC = () => {
    if (!selectedProposal) return;
    const rfcMarkdown = `# Architecture Refactoring Specification (RFC)
## Proposal: ${selectedProposal.title}
- **Proposal ID**: ${selectedProposal.id}
- **Target Rule**: ${selectedProposal.target_rule_id}
- **Type**: ${selectedProposal.refactoring_type}
- **Status**: ${selectedProposal.status} (Deterministic Simulation: ${selectedProposal.simulation_status})
- **Generated**: ${selectedProposal.created_at}

---

### 1. Problem Statement
${selectedProposal.problem_statement}

### 2. Proposed Architecture Design
${selectedProposal.proposed_design}

### 3. Affected Components & Files
#### Components:
${selectedProposal.affected_components.map((c) => `- \`${c}\``).join('\n')}

#### Files:
${selectedProposal.affected_files.map((f) => `- \`${f}\``).join('\n')}

### 4. Hypothetical Edge Mutations
\`\`\`json
${JSON.stringify(selectedProposal.hypothetical_edge_mutations, null, 2)}
\`\`\`

### 5. Deterministic Metric Deltas
\`\`\`json
${JSON.stringify(selectedProposal.simulated_metric_deltas, null, 2)}
\`\`\`

---
*Generated by CodeSentinel Phase 30 Architecture Intelligence Engine.*
`;
    const blob = new Blob([rfcMarkdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RFC-${selectedProposal.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-xl font-bold text-slate-100 flex items-center space-x-2.5">
            <Boxes className="w-6 h-6 text-cyan-400" />
            <span>AI Architectural Refactoring Hub</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Automated refactoring proposals for architectural cycles and bottlenecks with zero autonomous code modification.
          </p>
        </div>

        {selectedProposal && (
          <div className="flex items-center space-x-2.5">
            <button
              onClick={handleExportRFC}
              className="flex items-center space-x-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 text-xs font-semibold rounded-lg transition-colors"
            >
              <FileDown className="w-4 h-4 text-cyan-400" />
              <span>Export RFC Document</span>
            </button>
          </div>
        )}
      </div>

      {error && (
        <div className="p-3 rounded-lg bg-rose-950/40 border border-rose-800/80 text-xs text-rose-300 flex items-center space-x-2">
          <AlertTriangle className="w-4 h-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Main Workspace Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Proposals List */}
        <div className="lg:col-span-1 space-y-3">
          <span className="text-xs font-bold text-slate-300 uppercase tracking-wider block">
            Refactoring Proposals ({proposals.length})
          </span>

          <div className="space-y-2 max-h-[600px] overflow-y-auto">
            {proposals.map((prop) => (
              <button
                key={prop.id}
                onClick={() => setSelectedProposal(prop)}
                className={`w-full text-left p-3.5 rounded-xl border transition-all ${
                  selectedProposal?.id === prop.id
                    ? 'bg-slate-900 border-cyan-500/80 shadow-lg'
                    : 'bg-[#0D121D] border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 text-cyan-300 border border-slate-700">
                    {prop.target_rule_id}
                  </span>
                  <span
                    className={`text-[10px] font-bold px-2 py-0.5 rounded border ${
                      prop.simulation_status === 'VERIFIED_SIMULATION'
                        ? 'bg-emerald-950/60 text-emerald-300 border-emerald-800'
                        : 'bg-amber-950/60 text-amber-300 border-amber-800'
                    }`}
                  >
                    {prop.simulation_status === 'VERIFIED_SIMULATION' ? 'Verified Impact' : 'Simulated'}
                  </span>
                </div>

                <h3 className="text-xs font-bold text-slate-200 line-clamp-2 leading-snug">
                  {prop.title}
                </h3>
                <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">
                  {prop.problem_statement}
                </p>
              </button>
            ))}

            {proposals.length === 0 && !loading && (
              <div className="p-6 text-center text-xs text-slate-500 bg-[#0D121D] border border-dashed border-slate-800 rounded-xl">
                No active architectural smells or cycles detected.
              </div>
            )}
          </div>
        </div>

        {/* Right: Proposal Details & Deterministic Simulation View */}
        {selectedProposal && (
          <div className="lg:col-span-2 space-y-5">
            {/* Proposal Overview Card */}
            <div className="bg-[#0D121D] border border-slate-800 rounded-xl p-5 space-y-4">
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div>
                  <span className="text-[11px] font-mono text-cyan-400 font-bold uppercase">
                    {selectedProposal.refactoring_type.replace('_', ' ')}
                  </span>
                  <h2 className="text-sm font-bold text-slate-100 mt-0.5">
                    {selectedProposal.title}
                  </h2>
                </div>

                <span className="text-[10px] font-mono px-2.5 py-1 rounded bg-slate-800 text-slate-400 border border-slate-700">
                  {selectedProposal.status}
                </span>
              </div>

              {/* Problem & Design */}
              <div className="space-y-2 text-xs">
                <div>
                  <span className="font-semibold text-slate-400 uppercase text-[10px] tracking-wider block mb-1">
                    Problem Statement:
                  </span>
                  <p className="text-slate-300 bg-slate-950 p-2.5 rounded border border-slate-800">
                    {selectedProposal.problem_statement}
                  </p>
                </div>

                <div>
                  <span className="font-semibold text-slate-400 uppercase text-[10px] tracking-wider block mb-1">
                    Proposed Architectural Design:
                  </span>
                  <p className="text-slate-200 bg-slate-950 p-2.5 rounded border border-slate-800 leading-relaxed font-mono text-[11px]">
                    {selectedProposal.proposed_design}
                  </p>
                </div>
              </div>

              {/* Hypothetical Edge Mutations */}
              <div className="space-y-2">
                <span className="font-semibold text-slate-400 uppercase text-[10px] tracking-wider block">
                  Hypothetical Graph Edge Mutations:
                </span>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {selectedProposal.hypothetical_edge_mutations.map((mut, idx) => (
                    <div
                      key={idx}
                      className="p-2 rounded bg-slate-950 border border-slate-800 flex items-center justify-between text-xs font-mono"
                    >
                      <div className="flex items-center space-x-2">
                        <span
                          className={`text-[9px] font-bold px-1.5 py-0.5 rounded ${
                            mut.action === 'REMOVE'
                              ? 'bg-rose-950 text-rose-300 border border-rose-800'
                              : 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                          }`}
                        >
                          {mut.action}
                        </span>
                        <span className="text-slate-300">{mut.source}</span>
                        <ArrowRight className="w-3 h-3 text-slate-500" />
                        <span className="text-slate-300">{mut.target}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Simulated Metric Deltas Table */}
              <div className="space-y-2 pt-2 border-t border-slate-800">
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-slate-400 uppercase text-[10px] tracking-wider flex items-center space-x-1.5">
                    <Activity className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Deterministic Simulated Metric Deltas:</span>
                  </span>

                  <button
                    disabled={simulating}
                    onClick={handleSimulateRerun}
                    className="flex items-center space-x-1 px-2.5 py-1 text-[11px] font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 rounded border border-slate-700"
                  >
                    <RotateCcw className="w-3 h-3 text-cyan-400" />
                    <span>{simulating ? 'Simulating...' : 'Rerun Simulation'}</span>
                  </button>
                </div>

                <div className="overflow-x-auto rounded-lg border border-slate-800">
                  <table className="w-full text-xs text-left">
                    <thead className="bg-slate-900 text-slate-400 font-semibold text-[10px] uppercase">
                      <tr>
                        <th className="p-2.5">Component</th>
                        <th className="p-2.5">Afferent (Ca) Delta</th>
                        <th className="p-2.5">Efferent (Ce) Delta</th>
                        <th className="p-2.5">Instability (I) Delta</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800 font-mono text-[11px] text-slate-300">
                      {Object.entries(selectedProposal.simulated_metric_deltas || {}).map(([comp, delta]: any) => (
                        <tr key={comp} className="hover:bg-slate-900/40">
                          <td className="p-2.5 font-sans font-semibold text-slate-200">{comp}</td>
                          <td className="p-2.5">
                            {delta.delta_ca !== 0 ? (
                              <span className={delta.delta_ca < 0 ? 'text-amber-400' : 'text-slate-300'}>
                                {delta.delta_ca > 0 ? `+${delta.delta_ca}` : delta.delta_ca}
                              </span>
                            ) : (
                              '0'
                            )}
                          </td>
                          <td className="p-2.5">
                            {delta.delta_ce !== 0 ? (
                              <span className={delta.delta_ce < 0 ? 'text-emerald-400' : 'text-rose-400'}>
                                {delta.delta_ce > 0 ? `+${delta.delta_ce}` : delta.delta_ce}
                              </span>
                            ) : (
                              '0'
                            )}
                          </td>
                          <td className="p-2.5">
                            {delta.delta_instability !== 0 ? (
                              <span
                                className={`flex items-center space-x-1 ${
                                  delta.delta_instability < 0 ? 'text-emerald-400' : 'text-amber-400'
                                }`}
                              >
                                {delta.delta_instability < 0 ? (
                                  <TrendingDown className="w-3 h-3" />
                                ) : (
                                  <TrendingUp className="w-3 h-3" />
                                )}
                                <span>{delta.delta_instability.toFixed(2)}</span>
                              </span>
                            ) : (
                              '0.00'
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
