"""Unit tests for Phase 21 deterministic file and configuration fingerprinting."""

import os
from pathlib import Path
import pytest

from analyzer.config.settings import AnalysisConfig
from analyzer.incremental.config_fingerprint import compute_scoped_config_fingerprint
from analyzer.incremental.fingerprints import (
    compute_content_hash,
    compute_file_fingerprint,
    diff_fingerprints,
    is_generated_file,
    normalize_relative_path,
)
from analyzer.incremental.models import FileFingerprint


class TestPathNormalization:
    """Verifies canonical forward-slash path normalization and traversal defense."""

    def test_normalize_clean_paths(self):
        assert normalize_relative_path("foo/bar.py") == "foo/bar.py"
        assert normalize_relative_path("foo\\bar.py") == "foo/bar.py"
        assert normalize_relative_path("./foo/./bar.py") == "foo/bar.py"
        assert normalize_relative_path("/foo/bar.py/") == "foo/bar.py"

    def test_escape_boundary_rejected(self):
        with pytest.raises(ValueError, match="escapes repository boundary"):
            normalize_relative_path("../outside.py")

        with pytest.raises(ValueError, match="escapes repository boundary"):
            normalize_relative_path("foo/../../outside.py")


class TestContentHashing:
    """Verifies deterministic hashing and cross-platform CRLF normalization."""

    def test_crlf_lf_equivalence(self):
        crlf_content = b"def foo():\r\n    return 42\r\n"
        lf_content = b"def foo():\n    return 42\n"

        hash_crlf = compute_content_hash(crlf_content)
        hash_lf = compute_content_hash(lf_content)

        assert hash_crlf == hash_lf
        assert len(hash_crlf) == 64

    def test_str_and_bytes_equivalence(self):
        text = "console.log('hello world');\n"
        assert compute_content_hash(text) == compute_content_hash(text.encode("utf-8"))

    def test_distinct_content_distinct_hash(self):
        assert compute_content_hash("x = 1") != compute_content_hash("x = 2")


class TestGeneratedFiles:
    """Verifies detection of minified and auto-generated files."""

    def test_suffix_detection(self):
        assert is_generated_file("bundle.min.js") is True
        assert is_generated_file("service_pb2.py") is True
        assert is_generated_file("app.py") is False

    def test_header_marker_detection(self):
        header = "# @generated by protobuf compiler. DO NOT EDIT."
        assert is_generated_file("generated.py", content_preview=header) is True
        assert is_generated_file("normal.py", content_preview="# Normal file header") is False


class TestFileFingerprintCalculation:
    """Verifies computation of FileFingerprint models on disk."""

    def test_fingerprint_file(self, tmp_path):
        repo_root = tmp_path / "repo"
        repo_root.mkdir()
        src_file = repo_root / "src" / "main.py"
        src_file.parent.mkdir()
        src_file.write_bytes(b"print('hello')\n")

        fp = compute_file_fingerprint(
            abs_path=src_file,
            repo_root=repo_root,
            language="PYTHON",
            parser_version="1.0.0",
            schema_version="1.0.0",
        )

        assert fp is not None
        assert fp.path == "src/main.py"
        assert fp.language == "PYTHON"
        assert fp.size_bytes == 15
        assert len(fp.content_hash) == 64
        assert len(fp.compute_composite_hash()) == 64

    def test_nonexistent_file_returns_none(self, tmp_path):
        fp = compute_file_fingerprint(
            abs_path=tmp_path / "missing.py",
            repo_root=tmp_path,
            language="PYTHON",
        )
        assert fp is None


class TestDiffFingerprints:
    """Verifies diffing fingerprint states for modified, added, deleted, and renamed files."""

    def test_diff_operations(self):
        fp1 = FileFingerprint(path="a.py", content_hash="hash1", size_bytes=100, language="PYTHON")
        fp2 = FileFingerprint(path="b.py", content_hash="hash2", size_bytes=200, language="PYTHON")
        fp3 = FileFingerprint(path="c.py", content_hash="hash3", size_bytes=300, language="PYTHON")

        # Current state:
        # a.py modified (hash changed)
        # b.py unchanged
        # c.py deleted
        # d.py added (unique hash)
        # e.py renamed from c.py (same hash3 and size 300)
        fp1_mod = FileFingerprint(path="a.py", content_hash="hash1_mod", size_bytes=105, language="PYTHON")
        fp4_new = FileFingerprint(path="d.py", content_hash="hash4", size_bytes=400, language="PYTHON")
        fp5_renamed = FileFingerprint(path="e.py", content_hash="hash3", size_bytes=300, language="PYTHON")

        prev = {"a.py": fp1, "b.py": fp2, "c.py": fp3}
        curr = {"a.py": fp1_mod, "b.py": fp2, "d.py": fp4_new, "e.py": fp5_renamed}

        modified, added, deleted, renamed = diff_fingerprints(prev, curr)

        assert modified == {"a.py"}
        assert added == {"d.py"}
        assert deleted == set()  # c.py was detected as renamed to e.py
        assert renamed == {"c.py": "e.py"}


class TestScopedConfigFingerprinting:
    """Verifies that configuration digest scoping restricts invalidation strictly to affected layers."""

    def test_scoped_invalidation_isolation(self):
        base_cfg = AnalysisConfig(max_call_depth=5, enabled_rules=["SEC-PY-001"])
        fp_base = compute_scoped_config_fingerprint(base_cfg)

        # Alter call depth only
        depth_cfg = AnalysisConfig(max_call_depth=8, enabled_rules=["SEC-PY-001"])
        fp_depth = compute_scoped_config_fingerprint(depth_cfg)

        assert fp_depth.callgraph_hash != fp_base.callgraph_hash
        assert fp_depth.global_hash != fp_base.global_hash
        # Independent layers must remain IDENTICAL
        assert fp_depth.parsing_hash == fp_base.parsing_hash
        assert fp_depth.dependency_hash == fp_base.dependency_hash
        assert fp_depth.cfg_dataflow_hash == fp_base.cfg_dataflow_hash
        assert fp_depth.contract_hash == fp_base.contract_hash
        assert fp_depth.rules_hash == fp_base.rules_hash

    def test_rule_toggle_isolation(self):
        cfg1 = AnalysisConfig(enabled_rules=["SEC-PY-001"])
        cfg2 = AnalysisConfig(enabled_rules=["SEC-PY-001", "SEC-PY-002"])

        fp1 = compute_scoped_config_fingerprint(cfg1)
        fp2 = compute_scoped_config_fingerprint(cfg2)

        assert fp1.rules_hash != fp2.rules_hash
        # CFG, callgraph, and contract layers remain reusable
        assert fp1.parsing_hash == fp2.parsing_hash
        assert fp1.cfg_dataflow_hash == fp2.cfg_dataflow_hash
        assert fp1.callgraph_hash == fp2.callgraph_hash
        assert fp1.contract_hash == fp2.contract_hash
