"""Deterministic file fingerprinting and repository source diff engine (Phase 21)."""

import hashlib
import os
from pathlib import Path
import posixpath
from typing import Optional

from analyzer.incremental.models import FileFingerprint
from analyzer.models.metadata import DiscoveredFileMetadata

GENERATED_FILE_MARKERS = [
    "@generated",
    "do not edit",
    "auto-generated",
    "generated by",
    "code generated by",
]

GENERATED_FILE_SUFFIXES = [
    ".min.js",
    ".min.css",
    "_pb2.py",
    "_pb2_grpc.py",
    ".bundle.js",
    ".generated.ts",
    ".generated.js",
]


def normalize_relative_path(path: str | Path) -> str:
    """Canonicalize a relative file path to forward-slash normalized form.
    
    Guarantees:
    - Replaces backslashes with forward slashes.
    - Strips leading and trailing slashes.
    - Normalizes redundant segments via posixpath.normpath.
    - Prohibits path traversal outside repository root (e.g. '../').
    """
    raw_str = str(path).replace("\\", "/").strip("/")
    norm = posixpath.normpath(raw_str)
    if norm.startswith("../") or norm == "..":
        raise ValueError(f"Path escapes repository boundary: {raw_str}")
    return norm


def compute_content_hash(content: bytes | str) -> str:
    """Compute a deterministic SHA-256 digest of file content with CRLF normalization.
    
    Normalizes Windows CRLF ('\\r\\n') to Unix LF ('\\n') so identical code produces
    identical content digests across Windows, Linux, and macOS platforms.
    """
    if isinstance(content, str):
        raw_bytes = content.encode("utf-8", errors="replace")
    else:
        raw_bytes = content

    # Normalize CRLF to LF
    normalized = raw_bytes.replace(b"\r\n", b"\n")
    return hashlib.sha256(normalized).hexdigest()


def is_generated_file(rel_path: str, content_preview: Optional[str] = None) -> bool:
    """Determine whether a file is likely auto-generated or vendored/minified."""
    norm = rel_path.lower()
    for suffix in GENERATED_FILE_SUFFIXES:
        if norm.endswith(suffix):
            return True

    if content_preview:
        preview_lower = content_preview[:1024].lower()
        for marker in GENERATED_FILE_MARKERS:
            if marker in preview_lower:
                return True

    return False


def compute_file_fingerprint(
    abs_path: Path | str,
    repo_root: Path | str,
    language: str,
    parser_version: str = "1.0.0",
    schema_version: str = "1.0.0",
) -> Optional[FileFingerprint]:
    """Compute canonical FileFingerprint for a source file on disk.
    
    Verifies that realpath resides within repo_root (preventing symlink escape attacks).
    Returns None if file cannot be read or escapes repository.
    """
    path_obj = Path(abs_path)
    root_obj = Path(repo_root).resolve()

    try:
        real_path = path_obj.resolve()
        # Verify symlink boundary
        try:
            real_path.relative_to(root_obj)
        except ValueError:
            return None

        if not path_obj.is_file():
            return None

        raw_bytes = path_obj.read_bytes()
        size_bytes = len(raw_bytes)
        content_hash = compute_content_hash(raw_bytes)

        rel_path = normalize_relative_path(path_obj.relative_to(root_obj))
        text_preview = raw_bytes[:1024].decode("utf-8", errors="replace")
        generated = is_generated_file(rel_path, text_preview)

        return FileFingerprint(
            path=rel_path,
            content_hash=content_hash,
            size_bytes=size_bytes,
            language=language.upper(),
            parser_version=parser_version,
            analysis_schema_version=schema_version,
            is_generated=generated,
        )
    except (OSError, PermissionError):
        return None


def compute_repository_fingerprints(
    repo_root: Path | str,
    discovered_files: list[DiscoveredFileMetadata],
    parser_version: str = "1.0.0",
    schema_version: str = "1.0.0",
) -> dict[str, FileFingerprint]:
    """Compute canonical fingerprints for all discovered repository files."""
    fingerprints: dict[str, FileFingerprint] = {}
    root_path = Path(repo_root)

    for f in discovered_files:
        norm_rel = normalize_relative_path(f.relative_path)
        fp = compute_file_fingerprint(
            abs_path=f.path,
            repo_root=root_path,
            language=f.language,
            parser_version=parser_version,
            schema_version=schema_version,
        )
        if fp:
            fingerprints[norm_rel] = fp

    return fingerprints


def diff_fingerprints(
    previous: dict[str, FileFingerprint],
    current: dict[str, FileFingerprint],
) -> tuple[set[str], set[str], set[str], dict[str, str]]:
    """Compare previous and current fingerprint manifests.
    
    Returns:
        Tuple of (modified_paths, added_paths, deleted_paths, renamed_paths).
        renamed_paths maps old_path -> new_path for files with identical content hash and size.
    """
    prev_paths = set(previous.keys())
    curr_paths = set(current.keys())

    potential_added = curr_paths - prev_paths
    potential_deleted = prev_paths - curr_paths
    common = prev_paths & curr_paths

    modified: set[str] = set()
    for p in common:
        if previous[p].content_hash != current[p].content_hash:
            modified.add(p)

    # Detect file renames by matching content_hash and size
    renamed: dict[str, str] = {}
    unmatched_added = set(potential_added)
    unmatched_deleted = set(potential_deleted)

    # Build index of deleted files by content_hash and size
    deleted_by_hash: dict[tuple[str, int], list[str]] = {}
    for d in potential_deleted:
        key = (previous[d].content_hash, previous[d].size_bytes)
        deleted_by_hash.setdefault(key, []).append(d)

    for a in sorted(potential_added):
        key = (current[a].content_hash, current[a].size_bytes)
        candidates = deleted_by_hash.get(key, [])
        if len(candidates) == 1:
            # Unambiguous rename match
            old_path = candidates[0]
            renamed[old_path] = a
            unmatched_added.remove(a)
            unmatched_deleted.remove(old_path)
            deleted_by_hash[key].remove(old_path)

    return modified, unmatched_added, unmatched_deleted, renamed
