"""Policy proof obligation models for CodeSentinel (Phase 24).

Defines structured proof obligations generated by security policies and evaluated
against path-sensitive dataflow, authentication, and authorization evidence.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field
from analyzer.dataflow.taint.models import SinkCategory
from analyzer.dataflow.properties import SecurityProperty


class ObligationKind(str, Enum):
    """Classification of security invariant proof obligation."""
    REQUIRES_AUTHENTICATION = "REQUIRES_AUTHENTICATION"
    REQUIRES_AUTHORIZATION = "REQUIRES_AUTHORIZATION"
    REQUIRES_PROPERTY = "REQUIRES_PROPERTY"
    REQUIRES_VALIDATION = "REQUIRES_VALIDATION"
    REQUIRES_SANITIZER = "REQUIRES_SANITIZER"
    REQUIRES_PARAMETERIZATION = "REQUIRES_PARAMETERIZATION"


class ObligationEvaluationState(str, Enum):
    """Discrete verification outcome for a proof obligation."""
    PROVEN_SAFE = "PROVEN_SAFE"
    PROVEN_VIOLATION = "PROVEN_VIOLATION"
    UNKNOWN = "UNKNOWN"


class PolicyProofObligation(BaseModel):
    """Specific verifiable security obligation derived from an active policy."""
    model_config = ConfigDict(frozen=True)

    obligation_id: str
    policy_id: str
    kind: ObligationKind
    target_sink_category: SinkCategory
    required_property: Optional[SecurityProperty] = None
    required_permission: Optional[str] = None
    target_expression: str = ""
    file_path: str = ""
    line: int = 0
    state: ObligationEvaluationState = ObligationEvaluationState.UNKNOWN
    evidence_details: str = ""
    unknown_reason: Optional[str] = None
